### *Linear SVM*

In [2]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [4]:
iris = datasets.load_iris()
X = iris["data"][:, (2,3)]
y = (iris["target"] == 2).astype(np.int)

In [6]:
svm_clf = Pipeline([
    ("scaling", StandardScaler()),
    ("linear_svm", LinearSVC(C = 1, loss = "hinge"))
])
svm_clf.fit(X, y)

Pipeline(steps=[('scaling', StandardScaler()),
                ('linear_svm', LinearSVC(C=1, loss='hinge'))])

In [7]:
svm_clf.predict([[5.5, 1.7]])

array([1])

### *Polynomial SVM*

In [8]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.svm import LinearSVC

In [9]:
X, y = make_moons(n_samples = 100, noise = 0.15)
poly_svm = Pipeline([
    ("poly_features", PolynomialFeatures(degree = 3)),
    ("scaling", StandardScaler()),
    ("linear_svm", LinearSVC(C = 10, loss = "hinge"))
])
poly_svm.fit(X,y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaling', StandardScaler()),
                ('linear_svm', LinearSVC(C=10, loss='hinge'))])

In [12]:
poly_svm.predict([[2, 1]])

array([1])

In [18]:
from sklearn.svm import SVC
poly_kernel_svm = Pipeline([
    ("scaling", StandardScaler()),
    ("poly_svm", SVC(kernel = "poly", C = 5, degree = 3, coef0 = 1))
])
poly_kernel_svm.fit(X, y)

Pipeline(steps=[('scaling', StandardScaler()),
                ('poly_svm', SVC(C=5, coef0=1, kernel='poly'))])

In [19]:
poly_kernel_svm.predict([[2, 1]])

array([1])

### * Gaussian RBF Kernel*

In [6]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

rbf_kernel_svm_clf = Pipeline([
    ("scaling", StandardScaler()),
    ("svm_clf", SVC(kernel = "rbf", gamma = 5, C = 0.001))
])

rbf_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaling', StandardScaler()),
                ('svm_clf', SVC(C=0.001, gamma=5))])

In [7]:
from sklearn.svm import LinearSVR

svr_reg = LinearSVR(epsilon = 1.3)
svr_reg.fit(X, y)

LinearSVR(epsilon=1.3)

In [8]:
from sklearn.svm import SVR

svr_poly_reg = SVR(kernel = "poly", degree = 2, C = 100, epsilon = 0.1)
svr_poly_reg.fit(X, y)

SVR(C=100, degree=2, kernel='poly')